// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"server/internal/user"
)

// Injectors from wire.go:

func InitializeHandler(db *sql.DB) (*user.Handler, error) {
	handler := user.ProviderHandler()
	return handler, nil
}
